services:
  miplay:
    image: ghcr.io/juneix/miplay
    container_name: miplay
    network_mode: host
    restart: unless-stopped
    environment:
      WEB_PORT: 8300
      MIPLAY_HOST: ${MIPLAY_HOST:-}
    volumes:
      - ./conf:/app/conf
# 如需搭配 Shairport-Sync 使用，请取消注释
#  shairport-sync:
#    image: mikebrady/shairport-sync
#    container_name: airplay2
#    network_mode: host
#    restart: always
#    devices:
#      - /dev/snd:/dev/snd
#    cap_add:
#      - SYS_NICE